server:
  port: 9009

spring:
  application:
    name: notification-service
  config:
    import: optional:consul://${CONSUL_HOST:localhost}:8500
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      config:
        enabled: true
        prefixes: config,secrets
        format: PROPERTIES
        default-context: application
        watch:
          enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/master

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true

logging:
  level:
    org:
      springframework:
        web:
          reactive:
            result:
              method:
                annotation:
                  RequestMappingHandlerMapping: TRACE