replicaCount: 1

image:
  repository: openzipkin/zipkin-slim
  tag: "2.24.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9411

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

zipkin:
  storage:
    type: mem

# Опционально: переопределение имени
nameOverride: ""
fullnameOverride: ""