services:
  accounts-service-db:
    image: postgres:latest
    container_name: accounts_service_db_container
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: accounts_service_db
    ports:
      - "5430:5432"

  consul-server:
    image: hashicorp/consul:1.15
    container_name: consul-server
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"dc1", "log_level":"INFO", "server":true}
    ports:
      - "8500:8500" # UI
      - "8600:8600/udp" # DNS
      - "8300:8300" # Server RPC
      - "8301:8301" # Serf LAN
      - "8302:8302" # Serf WAN
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/status/leader" ]
      interval: 10s
      timeout: 5s
      retries: 5

  consul-config-loader:
    image: curlimages/curl:latest
    container_name: consul-config-loader
    volumes:
      - ./.docker:/docker
    command: [ "/bin/sh", "/docker/upload-to-consul.sh" ]
    depends_on:
      consul-server:
        condition: service_healthy

  consul-client:
    image: hashicorp/consul:1.15
    container_name: consul-client
    command: "agent -node=client-1 -join=consul-server -client=0.0.0.0"
    depends_on:
      - consul-server
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"dc1", "log_level":"INFO"}
    ports:
      - "8501:8500"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=keycloak
    ports:
      - "8080:8080"
    command:
      - start-dev