services:
  accounts-service-db:
    image: postgres:latest
    container_name: accounts_service_db_container
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: accounts_service_db
    ports:
      - "5430:5432"

  keycloak-secret-loader:
    build:
      context: ./.docker/keycloak-config-loader
      dockerfile: Dockerfile
    container_name: keycloak-secret-loader
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - CONSUL_URL=http://consul-server:8500
    volumes:
      - ./.docker:/docker
    command: >
      sh -c "
      echo 'Ожидание готовности Keycloak...' &&
      while ! curl -s http://keycloak:8080; do sleep 5; done &&
      echo 'Keycloak готов - начинаем получение секретов' &&
      chmod +x /app/scripts/get-secrets.sh &&
      sh /app/scripts/get-secrets.sh"
    depends_on:
      - keycloak
      - consul-server

  accounts-service:
    container_name: accounts-service
    build:
      context: ./accounts-service
      dockerfile: Dockerfile
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://accounts-service-db:5432/accounts_service_db
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
      - CONSUL_HOST=consul-client
      - CLIENT_SECRET=${ACCOUNTS_SERVICE_CLIENT_SECRET}
    ports:
      - "9001:9001"
    depends_on:
      - accounts-service-db
      - keycloak-secret-loader

  blocker-service:
    container_name: blocker-service
    build:
      context: ./blocker-service
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
      - CONSUL_HOST=consul-client
    ports:
      - "9008:9008"
    depends_on:
      - keycloak-secret-loader

  cash-service:
    container_name: cash-service
    build:
      context: ./cash-service
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
      - CONSUL_HOST=consul-client
      - CLIENT_SECRET=${CASH_SERVICE_CLIENT_SECRET}
    ports:
      - "9002:9002"
    depends_on:
      - keycloak-secret-loader

  exchange-generator-service:
    container_name: exchange-generator-service
    build:
      context: ./exchange-generator-service
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
      - CONSUL_HOST=consul-client
      - CLIENT_SECRET=${EXCHANGE_GENERATOR_SERVICE_CLIENT_SECRET}
    ports:
      - "9007:9007"
    depends_on:
      - keycloak-secret-loader

  exchange-service:
    container_name: exchange-service
    build:
      context: ./exchange-service
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
      - CONSUL_HOST=consul-client
    ports:
      - "9003:9003"
    depends_on:
      - keycloak-secret-loader

  front-ui:
    container_name: front-ui
    build:
      context: ./front-ui
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
      - CONSUL_HOST=consul-client
      - CLIENT_SECRET=${FRONT_UI_SERVICE_CLIENT_SECRET}
    ports:
      - "9000:9000"
    depends_on:
      - keycloak-secret-loader

  gateway-service:
    container_name: gateway-service
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
      - CONSUL_HOST=consul-client
    ports:
      - "9006:9006"
    depends_on:
      - keycloak-secret-loader

  notification-service:
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
      - CONSUL_HOST=consul-client
    ports:
      - "9009:9009"
    depends_on:
      - keycloak-secret-loader

  transfer-service:
    container_name: transfer-service
    build:
      context: ./transfer-service
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ISSUE_URL=http://keycloak:8080/realms/master
      - CONSUL_HOST=consul-client
      - CLIENT_SECRET=${TRANSFER_SERVICE_CLIENT_SECRET}
    ports:
      - "9004:9004"
    depends_on:
      - keycloak-secret-loader

  consul-server:
    image: hashicorp/consul:1.15
    container_name: consul-server
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"dc1", "log_level":"INFO", "server":true}
    ports:
      - "8500:8500" # UI
      - "8600:8600/udp" # DNS
      - "8300:8300" # Server RPC
      - "8301:8301" # Serf LAN
      - "8302:8302" # Serf WAN
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/status/leader" ]
      interval: 10s
      timeout: 5s
      retries: 5

  consul-config-loader:
    image: curlimages/curl:latest
    container_name: consul-config-loader
    volumes:
      - ./.docker:/docker
    command: [ "/bin/sh", "/docker/consul/upload-to-consul.sh" ]
    depends_on:
      consul-server:
        condition: service_healthy

  consul-client:
    image: hashicorp/consul:1.15
    container_name: consul-client
    command: "agent -node=client-1 -join=consul-server -client=0.0.0.0"
    depends_on:
      - consul-server
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"dc1", "log_level":"INFO"}
    ports:
      - "8501:8500"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=keycloak
    ports:
      - "8080:8080"
    command:
      - start-dev

  keycloak-config-loader:
    build:
      context: ./.docker/keycloak-config-loader
      dockerfile: Dockerfile
    container_name: keycloak-config-loader
    volumes:
      - ./.docker:/docker
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_REALM=master
    entrypoint: [ ]
    command: >
      /bin/sh -c "
      echo 'Ожидание готовности Keycloak...' &&
      while ! curl -s http://keycloak:8080; do
        sleep 5;
      done &&
      echo 'Keycloak готов - начинаем конфигурацию' &&
      echo 'Загрузка скоупов...' &&
      sh /app/scripts/upload-scopes-to-keycloak.sh &&
      echo 'Загрузка клиентов...' &&
      sh /app/scripts/upload-clients-to-keycloak.sh"
    depends_on:
      - keycloak
