server:
  port: 9003

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: exchange-service
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:29092}
    admin:
      client-id: exchange-service
      fail-fast: true
    consumer:
      group-id: exchange-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: '*'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URL:http://keycloak:8080/realms/master}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework.kafka: TRACE
    org.apache.kafka.clients.consumer: TRACE