server:
  port: 9002

spring:
  application:
    name: cash-service
  config:
    import: optional:consul://localhost:8500
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        prefixes: config
        format: PROPERTIES
        default-context: application
        watch:
          enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URL:http://keycloak:8080/realms/master}
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/master
        registration:
          cash-service-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: cash-service-client
            client-secret: 7NH6aciGchDEY7zy4KkJ5jlnGFXVWJmb
            scope: accounts.read,accounts.write,blocker.read
            clientAuthenticationMethod: client_secret_post