server:
  port: 9002

account:
  service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:9001}
blocker:
  service:
    url: ${BLOCKER_SERVICE_URL:http://localhost:9008}
notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:9009}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: cash-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URL:http://keycloak:8080/realms/master}
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/master
        registration:
          cash-service-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: cash-service-client
            client-secret: ${CLIENT_SECRET:7NH6aciGchDEY7zy4KkJ5jlnGFXVWJmb}
            scope: accounts.read,accounts.write,blocker.read,notification.write
            clientAuthenticationMethod: client_secret_post