server:
  port: 9007

spring:
  application:
    name: exchange-generator-service
  config:
    import: optional:consul://${CONSUL_HOST:localhost}:8500
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      config:
        enabled: true
        prefixes: config,secrets
        format: PROPERTIES
        default-context: application
        watch:
          enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/master
        registration:
          exchange-generator-service-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: exchange-generator-service-client
            client-secret: ${CLIENT_SECRET:YbvQksjI5zGe3Sy5LBPZsVZFXCdN0WrD}
            scope: exchange.write
            clientAuthenticationMethod: client_secret_post