server:
  port: 9007

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: exchange-generator-service
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:29092}
    admin:
      client-id: exchange-generator-service
      fail-fast: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/master
        registration:
          exchange-generator-service-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: exchange-generator-service-client
            client-secret: ${CLIENT_SECRET:YbvQksjI5zGe3Sy5LBPZsVZFXCdN0WrD}
            scope: exchange.write
            clientAuthenticationMethod: client_secret_post