apiVersion: v2
name: prometheus
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 56.6.0 # Замените на актуальную
    repository: https://prometheus-community.github.io/helm-charts