server:
  port: 9006

spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: api-gateway
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 15s
        tags: gateway
        prefer-ip-address: true
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: exchange-service-route
          uri: lb://exchange-service
          predicates:
            - Path=/exchange-service/**
          filters:
            - RewritePath=/exchange-service/?(?<segment>.*), /$\{segment}
        - id: accounts-service-route
          uri: lb://accounts-service
          predicates:
            - Path=/accounts-service/**
          filters:
            - RewritePath=/accounts-service/?(?<segment>.*), /$\{segment}
        - id: cash-service-route
          uri: lb://cash-service
          predicates:
            - Path=/cash-service/**
          filters:
            - RewritePath=/cash-service/?(?<segment>.*), /$\{segment}
        - id: transfer-service-route
          uri: lb://transfer-service
          predicates:
            - Path=/transfer-service/**
          filters:
            - RewritePath=/transfer-service/?(?<segment>.*), /$\{segment}
        - id: blocker-service-route
          uri: lb://blocker-service
          predicates:
            - Path=/blocker-service/**
          filters:
            - RewritePath=/blocker-service/?(?<segment>.*), /$\{segment}

#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            token-uri: http://keycloak:8080/realms/master/protocol/openid-connect/token
#        registration:
#          gateway-client:
#            provider: keycloak
#            client-id: gateway_client
#            client-secret: jHW3UNzpxKQAg8vMpBb83ae1anM5R2PO
#            scope: resource.read
#            authorization-grant-type: client_credentials

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    reactor.netty.http.client: DEBUG