server:
  port: 9000

account:
  service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:9001}
cash:
  service:
    url: ${CASH_SERVICE_URL:http://localhost:9002}
exchange:
  service:
    url: ${EXCHANGE_SERVICE_URL:http://localhost:9003}
transfer:
  service:
    url: ${TRANSFER_SERVICE_URL:http://localhost:9004}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: front-ui
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/master
        registration:
          front-ui-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: front-ui-client
            client-secret: ${CLIENT_SECRET:LLtTlDhsJJ2lfN5c0oHtcb0zdLQyvkXQ}
            scope: exchange.read,accounts.read,accounts.write,cash.write,transfer.write
            clientAuthenticationMethod: client_secret_post