server:
  port: 9004

spring:
  application:
    name: transfer-service
  config:
    import: optional:consul://localhost:8500
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        prefixes: config
        format: PROPERTIES
        default-context: application
        watch:
          enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URL:http://keycloak:8080/realms/master}
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/master
        registration:
          transfer-service-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: transfer-service-client
            client-secret: Sbv2HTFhjQhdlt49JVLukoXH1Dlf05sv
            scope: accounts.read,accounts.write,blocker.read,exchange.read,notification.write
            clientAuthenticationMethod: client_secret_post

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true