server:
  port: 9004

account:
  service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:9001}
blocker:
  service:
    url: ${BLOCKER_SERVICE_URL:http://localhost:9008}
exchange:
  service:
    url: ${EXCHANGE_SERVICE_URL:http://localhost:9003}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: transfer-service
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:29092}
    admin:
      client-id: transfer-service
      fail-fast: true
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URL:http://keycloak:8080/realms/master}
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/master
        registration:
          transfer-service-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: transfer-service-client
            client-secret: ${CLIENT_SECRET:Sbv2HTFhjQhdlt49JVLukoXH1Dlf05sv}
            scope: accounts.read,accounts.write,blocker.read,exchange.read,notification.write
            clientAuthenticationMethod: client_secret_post

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://127.0.0.1:9411}/api/v2/spans # Эндпоинт Zipkin для приёма спанов
  tracing:
    sampling:
      probability: 1 # Сэмплируем все запросы