replicaCount: 1

image:
  repository: bankapp-accounts-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9001

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: accounts-service.test.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

environment:
  KEYCLOAK_ISSUE_URL: http://keycloak:8080/realms/master
  KAFKA_URL: kafka.kafka.svc.cluster.local:9092
  CLIENT_SECRET: PAsZ470oShhYzY9qlVy35yty0tcWZhp7

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

config:
  database_url: "r2dbc:postgresql://{{ .Release.Name }}-accounts-service-db:5432/accounts_service_db"
  database_username: "sa"