server:
  port: 9008

spring:
  application:
    name: blocker-service
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URL:http://keycloak:8080/realms/master}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true