server:
  port: 9008

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: blocker-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URL:http://keycloak:8080/realms/master}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://127.0.0.1:9411}/api/v2/spans # Эндпоинт Zipkin для приёма спанов
  tracing:
    sampling:
      probability: 1 # Сэмплируем все запросы