server:
  port: 9008

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: blocker-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URL:http://keycloak:8080/realms/master}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true