server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: accounts-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5430/accounts_service_db
    username: sa
    password: sa
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:29092}
    admin:
      client-id: accounts-service
      fail-fast: true
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUE_URL:http://keycloak:8080/realms/master}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUE_URL:http://keycloak:8080/realms/master}
        registration:
          accounts-service-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: accounts-service-client
            client-secret: ${CLIENT_SECRET:PAsZ470oShhYzY9qlVy35yty0tcWZhp7}
            scope: notification.write
            clientAuthenticationMethod: client_secret_post

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true