apiVersion: v2
name: bankapp
description: Bank Application Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "14.2.3"
    repository: "https://charts.bitnami.com/bitnami"
    alias: accounts-service-db
    condition: accounts-service-db.enabled
  - name: accounts-service
    version: 0.1.0
    repository: "file://./charts/accounts-service"
  - name: blocker-service
    version: 0.1.0
    repository: "file://./charts/blocker-service"
  - name: cash-service
    version: 0.1.0
    repository: "file://./charts/cash-service"
  - name: exchange-generator-service
    version: 0.1.0
    repository: "file://./charts/exchange-generator-service"
  - name: exchange-service
    version: 0.1.0
    repository: "file://./charts/exchange-service"
  - name: front-ui
    version: 0.1.0
    repository: "file://./charts/front-ui"
  - name: notification-service
    version: 0.1.0
    repository: "file://./charts/notification-service"
  - name: transfer-service
    version: 0.1.0
    repository: "file://./charts/transfer-service"