replicaCount: 1

image:
  repository: bankapp-front-ui
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: front-ui.test.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

environment:
  KEYCLOAK_ISSUE_URL: http://keycloak:8080/realms/master
  ACCOUNT_SERVICE_URL: http://{{ .Release.Name }}-accounts-service:9001
  CASH_SERVICE_URL: http://{{ .Release.Name }}-cash-service:9002
  EXCHANGE_SERVICE_URL: http://{{ .Release.Name }}-exchange-service:9003
  TRANSFER_SERVICE_URL: http://{{ .Release.Name }}-transfer-service:9004

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80