replicaCount: 1

image:
  repository: bankapp-exchange-generator-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9007

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: exchange-generator-service.test.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

environment:
  KEYCLOAK_ISSUE_URL: http://keycloak:8080/realms/master
  KAFKA_URL: kafka.kafka.svc.cluster.local:9092

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80